# http://sparkjava.com/tutorials/docker
FROM amazoncorretto:8

RUN yum install -y maven

WORKDIR /code

# Prepare by downloading dependencies
ADD pom.xml /code/pom.xml
RUN ["mvn", "dependency:resolve"]
RUN ["mvn", "verify"]

# Adding source, compile and package into a fat jar
ADD src /code/src
RUN ["mvn", "package"]

CMD ["java", "-jar", "target/sparkexample-jar-with-dependencies.jar"]
