FROM python:3.10.8

# https://fastapi.tiangolo.com/deployment/docker/
WORKDIR /code

# 
COPY ./requirements.txt /code/requirements.txt

# 
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

RUN opentelemetry-bootstrap -a install

# 
COPY ./app /code/app
# 
CMD ["opentelemetry-instrument", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "5001"]

